encoding: utf-8

# Site settings
title: Laboratório de Aplicações de Informática em Saúde
email: fatima.nunes@usp.br
description: Laboratório de Aplicações de Informática em Saúde
header-img: "img/code.jpg"

baseurl: # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://lapis.each.usp.br" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: facebook
    url: https://www.facebook.com/lapisusp
  - title: twitter
    url: https://twitter.com/lapis_usp
  - title: instagram
    url: https://www.instagram.com/lapisusp/


phone: "(11) 3018 1040"

collections:
  members:
    output: True
  researches:
    output: true
    permalink: /research/:name
  projects:
    output: true
    permalink: /project/:name
  softwares:
    output: true
    permalink: /software/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      type: "project"
  - scope:
      path: ""
      type: "researches"
    values:
      layout: "research"
      type: "research"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
      type: "member"
  - scope:
      path: ""
      type: "softwares"
    values:
      layout: "software"
      type: "software"
  - scope:
      type: "members"
    values:
      language: "pt"
      permalink: /pt/member/:name/
  - scope:
      path: "_members/en"
      type: "members"
    values:
      language: "en"
      permalink: /en/member/:name/
  - scope:
      path: "_projects/pt"
      type: "projects"
    values:
      language: "pt"
      permalink: /pt/project/:name/
  - scope:
      path: "_projects/en"
      type: "projects"
    values:
      language: "en"
      permalink: /en/project/:name/
  - scope:
      path: "_researches/pt"
      type: "researches"
    values:
      language: "pt"
      permalink: /pt/research/:name/
  - scope:
      path: "_researches/en"
      type: "researches"
    values:
      language: "en"
      permalink: /en/research/:name/
  - scope:
      path: "_softwares/pt"
      type: "softwares"
    values:
      language: "pt"
      permalink: /pt/software/:name/
  - scope:
      path: "_softwares/en"
      type: "softwares"
    values:
      language: "en"
      permalink: /en/software/:name/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules","gulpfile.js","package.json","package.json.lock","README.md", ".idea"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from, jekyll-sitemap]
